In [1]:
%run feature_extraction.ipynb
from sklearn.metrics import confusion_matrix,accuracy_score
# get the feature with flatten feature vector
to_flatten = True
_DATA_PATH = 'data/'
_CLASS_LABELS_Neutral = ["Neutral"]
_CLASS_LABELS_Sad = ["Sad"]
_CLASS_LABELS_Anger = ["Angry"]
_CLASS_LABELS_Happy = ["Happy"]
data_nuetral , labels = get_data(_DATA_PATH, class_labels=_CLASS_LABELS_Neutral,
                            flatten=to_flatten)
data_sad , labels = get_data(_DATA_PATH, class_labels=_CLASS_LABELS_Sad,
                            flatten=to_flatten)
data_anger , labels = get_data(_DATA_PATH, class_labels=_CLASS_LABELS_Anger,
                            flatten=to_flatten)
data_happy, labels = get_data(_DATA_PATH, class_labels=_CLASS_LABELS_Happy,
                            flatten=to_flatten)

curdir: C:\Users\Amrutha\Desktop\ml_2020_project\speech_proj_2_mlp_final_version_2
started reading folder Neutral
C:\Users\Amrutha\Anaconda3\lib\site-packages\scipy\io\wavfile.py:254: WavFileWarning: Chunk (non-data) not understood, skipping it.
  WavFileWarning)


['.ipynb_checkpoints', 'ANN_model_.h5', 'compariaion_accuracy.png', 'data', 'feature_extraction.ipynb', 'LSTM_best_model.h5', 'mel_spectogram.png', 'Model.ipynb', 'model_in_json.json', 'normalised_version.png', 'nueral.ipynb', 'output', 'plot_graph.ipynb', 'predict.ipynb', 'project_notes.txt', 'testing.ipynb', 'test_Cases.ipynb', 'trainig.ipynb', 'wave.png', 'wave_spectogram.png']
convert stereo to mono


ended reading folder Neutral
curdir: C:\Users\Amrutha\Desktop\ml_2020_project\speech_proj_2_mlp_final_version_2
started reading folder Sad


['.ipynb_checkpoints', 'ANN_model_.h5', 'compariaion_accuracy.png', 'data', 'feature_extraction.ipynb', 'LSTM_best_model.h5', 'mel_spectogram.png', 'Model.ipynb', 'model_in_json.json', 'normalised_version.png', 'nueral.ipynb', 'output', 'plot_graph.ipynb', 'predict.ipynb', 'project_notes.txt', 'testing.ipynb', 'test_Cases.ipynb', 'trainig.ipynb', 'wave.png', 'wave_spectogram.png']


C:\Users\Amrutha\Anaconda3\lib\site-packages\ipykernel_launcher.py:85: RuntimeWarning: invalid value encountered in log10
ended reading folder Sad
curdir: C:\Users\Amrutha\Desktop\ml_2020_project\speech_proj_2_mlp_final_version_2
started reading folder Angry


['.ipynb_checkpoints', 'ANN_model_.h5', 'compariaion_accuracy.png', 'data', 'feature_extraction.ipynb', 'LSTM_best_model.h5', 'mel_spectogram.png', 'Model.ipynb', 'model_in_json.json', 'normalised_version.png', 'nueral.ipynb', 'output', 'plot_graph.ipynb', 'predict.ipynb', 'project_notes.txt', 'testing.ipynb', 'test_Cases.ipynb', 'trainig.ipynb', 'wave.png', 'wave_spectogram.png']


ended reading folder Angry
curdir: C:\Users\Amrutha\Desktop\ml_2020_project\speech_proj_2_mlp_final_version_2
started reading folder Happy


['.ipynb_checkpoints', 'ANN_model_.h5', 'compariaion_accuracy.png', 'data', 'feature_extraction.ipynb', 'LSTM_best_model.h5', 'mel_spectogram.png', 'Model.ipynb', 'model_in_json.json', 'normalised_version.png', 'nueral.ipynb', 'output', 'plot_graph.ipynb', 'predict.ipynb', 'project_notes.txt', 'testing.ipynb', 'test_Cases.ipynb', 'trainig.ipynb', 'wave.png', 'wave_spectogram.png']
convert stereo to mono


ended reading folder Happy


In [2]:
# get current working directory 
nb_dir = os.path.split(os.getcwd())[0]
if nb_dir not in sys.path:
    sys.path.append(nb_dir)
print(os.getcwd())

C:\Users\Amrutha\Desktop\ml_2020_project\speech_proj_2_mlp_final_version_2


In [3]:
# load mlp model 
model = pickle.load(open('ANN_model_.h5', "rb"))

In [4]:
# reshape the feature vector to fit the model
size = data_nuetral.shape
print(data_nuetral.shape)
for i in range(size[0]):
    if len(data_nuetral[i]) <= 7722:
        l = 7722 - len(data_nuetral[i])
        data_nuetral[i] = np.append(data_nuetral[i],np.zeros(l))
    else:
        data_nuetral[i] = data_nuetral[i][:7722]
data_nuetral = np.asarray([np.asarray(row, dtype=float) for row in data_nuetral], dtype=float)

print(" TESTING FOR NUETRAL EMOTION ACCURACY WITH MLP MODEL ")
y_pred = model.predict(data_nuetral)
y_test = [0] * 257
cm = confusion_matrix(y_test,y_pred)
accuracy = accuracy_score(y_test,y_pred)
print("confusion matrics=",cm)
print("  ")
print(" accuracy=",accuracy*100)

(257,)
 TESTING FOR NUETRAL EMOTION ACCURACY WITH MLP MODEL 
confusion matrics= [[241   4  12]
 [  0   0   0]
 [  0   0   0]]
  
 accuracy= 93.77431906614785


In [5]:
# reshape the feature vector to fit the model
size = data_sad.shape
print(data_sad.shape)
for i in range(size[0]):
    if len(data_sad[i]) <= 7722:
        l = 7722 - len(data_sad[i])
        data_sad[i] = np.append(data_sad[i],np.zeros(l))
    else:
        data_sad[i] = data_sad[i][:7722]
data_sad = np.asarray([np.asarray(row, dtype=float) for row in data_sad], dtype=float)

print(" TESTING FOR SAD EMOTION ACCURACY WITH MLP MODEL ")
y_pred = model.predict(data_sad)
y_test = [3] * size[0]
y_pred = model.predict(data_sad)
cm = confusion_matrix(y_test,y_pred)
accuracy = accuracy_score(y_test,y_pred)
print("confusion matrics=",cm)
print("  ")
print(" accuracy=",accuracy*100)

(256,)
 TESTING FOR SAD EMOTION ACCURACY WITH MLP MODEL 
confusion matrics= [[  0   0   0   0]
 [  0   0   0   0]
 [  0   0   0   0]
 [  9   1   8 238]]
  
 accuracy= 92.96875


In [6]:
# reshape the feature vector to fit the model
size = data_anger.shape
print(data_anger.shape)
for i in range(size[0]):
    if len(data_anger[i]) <= 7722:
        l = 7722 - len(data_anger[i])
        data_anger[i] = np.append(data_anger[i],np.zeros(l))
    else:
        data_anger[i] = data_anger[i][:7722]
data_anger = np.asarray([np.asarray(row, dtype=float) for row in data_anger], dtype=float)

print(" TESTING FOR ANGER EMOTION ACCURACY WITH MLP MODEL ")
y_pred = model.predict(data_anger)
y_test = [1] * size[0]
y_pred = model.predict(data_anger)
cm = confusion_matrix(y_test,y_pred)
accuracy = accuracy_score(y_test,y_pred)
print("confusion matrics=",cm)
print("  ")
print(" accuracy=",accuracy*100)

(254,)
 TESTING FOR ANGER EMOTION ACCURACY WITH MLP MODEL 
confusion matrics= [[241   8   5]
 [  0   0   0]
 [  0   0   0]]
  
 accuracy= 94.88188976377953


In [7]:
# reshape the feature vector to fit the model
size = data_happy.shape
print(data_happy.shape)
for i in range(size[0]):
    if len(data_happy[i]) <= 7722:
        l = 7722 - len(data_happy[i])
        data_happy[i] = np.append(data_happy[i],np.zeros(l))
    else:
        data_happy[i] = data_happy[i][:7722]
data_happy = np.asarray([np.asarray(row, dtype=float) for row in data_happy], dtype=float)

print(" TESTING FOR HAPPY EMOTION ACCURACY WITH MLP MODEL ")
y_pred = model.predict(data_happy)
y_test = [2] * size[0]
y_pred = model.predict(data_happy)
cm = confusion_matrix(y_test,y_pred)
accuracy = accuracy_score(y_test,y_pred)
print("confusion matrics=",cm)
print("  ")
print(" accuracy=",accuracy*100)

(255,)
 TESTING FOR HAPPY EMOTION ACCURACY WITH MLP MODEL 
confusion matrics= [[  0   0   0   0]
 [  0   0   0   0]
 [  7  19 214  15]
 [  0   0   0   0]]
  
 accuracy= 83.92156862745098


In [8]:
# load LSTM model
# load lstm model
from keras.models import load_model
from keras.models import model_from_json
import json

with open('model_in_json.json','r') as f:
    model_json = json.load(f)
model = model_from_json(model_json)
model.load_weights('LSTM_best_model.h5')

Using TensorFlow backend.
C:\Users\Amrutha\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Amrutha\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Amrutha\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Amrutha\Anaconda3\lib\site-packages\tensorflow\python\framework\d

Instructions for updating:
Colocations handled automatically by placer.


In [9]:
# reshape the feature vector 
size = data_nuetral.shape
print(data_nuetral.shape)
for i in range(size[0]):
    if len(data_nuetral[i]) <= 7722:
        l = 7722 - len(data_nuetral[i])
#         print("asd",l)
        data_nuetral[i] = np.append(data_nuetral[i],np.zeros(l))
    else:
        data_nuetral[i] = data_nuetral[i][:7722]
data_nuetral = np.asarray([np.asarray(row, dtype=float) for row in data_nuetral], dtype=float)
data_nuetral = np.resize(data_nuetral, (size[0],198, 39))
print(data_anger.shape)

%run predict.ipynb
print(" TESTING FOR NUETRAL EMOTION ACCURACY WITH LSTM MODEL ")
y_pred = predict(data_nuetral,classifier='LSTM')
print(y_pred)
y_test = [0] * size[0]
# y_pred = predict_one(data_nuetral,classifier='LSTM')
cm = confusion_matrix(y_test,y_pred)
accuracy = accuracy_score(y_test,y_pred)
print("confusion matrics=",cm)
print("  ")
print(" accuracy=",accuracy*100)

(257, 7722)
(254, 7722)
 TESTING FOR NUETRAL EMOTION ACCURACY WITH LSTM MODEL 
(0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 3, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 2, 0, 0, 3, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 3)
confusion matrics= [[244   1   2  10]
 [  0   0   0   0]
 [  0   0   0   0]
 [  0   0   0   0]]
  
 accuracy= 94.94163424124513


In [10]:
# reshape the feature vector 
size = data_sad.shape
print(data_sad.shape)
for i in range(size[0]):
    if len(data_sad[i]) <= 7722:
        l = 7722 - len(data_sad[i])
#         print("asd",l)
        data_sad[i] = np.append(data_sad[i],np.zeros(l))
    else:
        data_sad[i] = data_sad[i][:7722]
data_sad = np.asarray([np.asarray(row, dtype=float) for row in data_sad], dtype=float)
data_sad = np.resize(data_sad, (size[0],198, 39))
print(data_sad.shape)

print(" TESTING FOR SAD EMOTION ACCURACY WITH LSTM MODEL ")
y_pred = predict(data_sad,classifier='LSTM')
y_test = [3] * size[0]
cm = confusion_matrix(y_test,y_pred)
accuracy = accuracy_score(y_test,y_pred)
print("confusion matrics=",cm)
print("  ")
print(" accuracy=",accuracy*100)

(256, 7722)
(256, 198, 39)
 TESTING FOR SAD EMOTION ACCURACY WITH LSTM MODEL 
confusion matrics= [[  0   0   0   0]
 [  0   0   0   0]
 [  0   0   0   0]
 [  5   1   6 244]]
  
 accuracy= 95.3125


In [11]:
# reshape the feature vector 
size = data_anger.shape
print(data_anger.shape)
for i in range(size[0]):
    if len(data_anger[i]) <= 7722:
        l = 7722 - len(data_anger[i])
#         print("asd",l)
        data_anger[i] = np.append(data_anger[i],np.zeros(l))
    else:
        data_anger[i] = data_anger[i][:7722]
data_anger = np.asarray([np.asarray(row, dtype=float) for row in data_anger], dtype=float)
data_anger = np.resize(data_anger, (size[0],198, 39))
print(data_anger.shape)

print(" TESTING FOR ANGER EMOTION ACCURACY WITH LSTM MODEL ")
y_pred = predict(data_anger,classifier='LSTM')
y_test = [1] * size[0]
cm = confusion_matrix(y_test,y_pred)
accuracy = accuracy_score(y_test,y_pred)
print("confusion matrics=",cm)
print("  ")
print(" accuracy=",accuracy*100)

(254, 7722)
(254, 198, 39)
 TESTING FOR ANGER EMOTION ACCURACY WITH LSTM MODEL 
confusion matrics= [[243   8   3]
 [  0   0   0]
 [  0   0   0]]
  
 accuracy= 95.66929133858267


In [12]:
# reshape the feature vector 
size = data_happy.shape
print(data_happy.shape)
for i in range(size[0]):
    if len(data_happy[i]) <= 7722:
        l = 7722 - len(data_happy[i])
#         print("asd",l)
        data_happy[i] = np.append(data_happy[i],np.zeros(l))
    else:
        data_happy[i] = data_happy[i][:7722]
data_happy = np.asarray([np.asarray(row, dtype=float) for row in data_happy], dtype=float)
data_happy = np.resize(data_happy, (size[0],198, 39))
print(data_happy.shape)

print(" TESTING FOR HAPPY EMOTION ACCURACY WITH LSTM MODEL ")
y_pred = predict(data_happy,classifier='LSTM')
y_test = [2] * size[0]
cm = confusion_matrix(y_test,y_pred)
accuracy = accuracy_score(y_test,y_pred)
print("confusion matrics=",cm)
print("  ")
print(" accuracy=",accuracy*100)

(255, 7722)
(255, 198, 39)
 TESTING FOR HAPPY EMOTION ACCURACY WITH LSTM MODEL 
confusion matrics= [[  0   0   0   0]
 [  0   0   0   0]
 [  5  10 232   8]
 [  0   0   0   0]]
  
 accuracy= 90.98039215686275
